package com.xtramile.docapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ElementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertElementAllPropertiesEquals(Element expected, Element actual) {
        assertElementAutoGeneratedPropertiesEquals(expected, actual);
        assertElementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertElementAllUpdatablePropertiesEquals(Element expected, Element actual) {
        assertElementUpdatableFieldsEquals(expected, actual);
        assertElementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertElementAutoGeneratedPropertiesEquals(Element expected, Element actual) {
        assertThat(expected)
            .as("Verify Element auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertElementUpdatableFieldsEquals(Element expected, Element actual) {
        assertThat(expected)
            .as("Verify Element relevant properties")
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertElementUpdatableRelationshipsEquals(Element expected, Element actual) {
        assertThat(expected)
            .as("Verify Element relationships")
            .satisfies(e -> assertThat(e.getPage()).as("check page").isEqualTo(actual.getPage()));
    }
}
