package com.xtramile.docapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FormVariableAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormVariableAllPropertiesEquals(FormVariable expected, FormVariable actual) {
        assertFormVariableAutoGeneratedPropertiesEquals(expected, actual);
        assertFormVariableAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormVariableAllUpdatablePropertiesEquals(FormVariable expected, FormVariable actual) {
        assertFormVariableUpdatableFieldsEquals(expected, actual);
        assertFormVariableUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormVariableAutoGeneratedPropertiesEquals(FormVariable expected, FormVariable actual) {
        assertThat(expected)
            .as("Verify FormVariable auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormVariableUpdatableFieldsEquals(FormVariable expected, FormVariable actual) {
        assertThat(expected)
            .as("Verify FormVariable relevant properties")
            .satisfies(e -> assertThat(e.getSectionCode()).as("check sectionCode").isEqualTo(actual.getSectionCode()))
            .satisfies(e -> assertThat(e.getSectionName()).as("check sectionName").isEqualTo(actual.getSectionName()))
            .satisfies(e -> assertThat(e.getFormVariableType()).as("check formVariableType").isEqualTo(actual.getFormVariableType()))
            .satisfies(e -> assertThat(e.getOrderIndex()).as("check orderIndex").isEqualTo(actual.getOrderIndex()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormVariableUpdatableRelationshipsEquals(FormVariable expected, FormVariable actual) {
        // empty method
    }
}
