package com.xtramile.docapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageAllPropertiesEquals(Page expected, Page actual) {
        assertPageAutoGeneratedPropertiesEquals(expected, actual);
        assertPageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageAllUpdatablePropertiesEquals(Page expected, Page actual) {
        assertPageUpdatableFieldsEquals(expected, actual);
        assertPageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageAutoGeneratedPropertiesEquals(Page expected, Page actual) {
        assertThat(expected)
            .as("Verify Page auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageUpdatableFieldsEquals(Page expected, Page actual) {
        assertThat(expected)
            .as("Verify Page relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPageUpdatableRelationshipsEquals(Page expected, Page actual) {
        assertThat(expected)
            .as("Verify Page relationships")
            .satisfies(e -> assertThat(e.getSection()).as("check section").isEqualTo(actual.getSection()));
    }
}
